/**
 * Identity and behaviour for this application.
 *
 * Generated by apps/build.mjs. Edit the definitions there rather than here,
 * so the four applications stay in step.
 */

export const config = {
  slug: "04-keyring",
  theme: "keyring",
  flagName: "FLAG_KID",
  flagSku: "NW-TRD-904",
  description: "Token signing services for Northwind Supply Co.",
  blurb: "One signing service issues session tokens for every internal application, so keys rotate in one place.",
  nav: [["/","Overview"],["/catalogue","Catalogue"],["/orders","Orders"],["/support","Support"]],
};

export const APP_SLUG = config.slug;
