/**
 * Identity and behaviour for this application.
 *
 * Generated by apps/build.mjs. Edit the definitions there rather than here,
 * so the four applications stay in step.
 */

export const config = {
  slug: "03-reflector",
  theme: "reflector",
  flagName: "FLAG_XSS",
  flagSku: "NW-TRD-903",
  description: "Catalogue search for Northwind Supply Co.",
  blurb: "Four thousand lines, one search box. The index updates nightly from the supplier feed.",
  nav: [["/","Overview"],["/search","Search"],["/orders","Orders"],["/support","Support"]],
};

export const APP_SLUG = config.slug;
