/**
 * Identity and behaviour for this application.
 *
 * Generated by apps/build.mjs. Edit the definitions there rather than here,
 * so the four applications stay in step.
 */

export const config = {
  slug: "01-session-forge",
  theme: "sessionForge",
  flagName: "FLAG_JWT",
  flagSku: "NW-TRD-901",
  description: "Workforce identity and session handling for Northwind Supply Co.",
  blurb: "Every employee signs in here. Sessions are stateless, which keeps our sign-in latency low across regions.",
  nav: [["/","Overview"],["/catalogue","Catalogue"],["/orders","Orders"],["/support","Support"]],
};

export const APP_SLUG = config.slug;
