/**
 * Identity and behaviour for this application.
 *
 * Generated by apps/build.mjs. Edit the definitions there rather than here,
 * so the four applications stay in step.
 */

export const config = {
  slug: "02-clearance",
  theme: "clearance",
  flagName: "FLAG_SQLI",
  flagSku: "NW-TRD-902",
  description: "Trade pricing and clearance levels for Northwind Supply Co.",
  blurb: "Trade customers see supplier pricing directly. Clearance decides which price list an account sees.",
  nav: [["/","Overview"],["/catalogue","Catalogue"],["/orders","Orders"],["/support","Support"]],
};

export const APP_SLUG = config.slug;
